name: golang-pipeline

on:
  push:
    tags: # Запускать задачу при пуше тега
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23 # Используется контейнер с Go 1.23
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test ./... # Запуск тестов для всех пакетов

      - name: Vet
        run: go vet ./... # Проверка кода с помощью vet

  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test # Задача deploy будет выполняться только после успешного выполнения тестов
    if: startsWith(github.ref, 'refs/tags') # Выполнять только при пуше тега
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Имя пользователя из секретов
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }} # Токен доступа из секретов

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: adam048/hello-golang # Укажите правильное имя репозитория Docker Hub

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . # Контекст сборки — текущая директория
          push: true # Пушить образ после сборки
          tags: ${{ steps.meta.outputs.tags }} # Автоматически сгенерированные теги
          labels: ${{ steps.meta.outputs.labels }} # Автоматически сгенерированные метки
